# ---
# - apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present
#   environment: proxy_env
# - apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present
#   environment: proxy_env

# - debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select' unseen=false

# - name: Copy PGP key for Oracle into place
#   template: src=oracle-pgp-key dest=/home/{{ hadoop_user }}/.ssh/oracle-pgp-key owner={{ hadoop_user }} mode=0600

# - apt_key: file=/home/{{ hadoop_user }}/.ssh/oracle-pgp-key

# - name: Install Java
#   apt: pkg=oracle-java8-installer state=present update_cache=true
#   environment: proxy_env
---
- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Install python-software-properties
  become: yes
  apt: name=python-software-properties state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8:1
  become: yes
  apt: name={{item}} state=latest
  loop:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
  
- lineinfile: dest=/home/hadoop/.bashrc regexp="^export JAVA_HOME" line="export JAVA_HOME=/usr/lib/jvm/java-8-oracle"
